### ISSUE TITLE
Taskbar style errors

### ISSUE THREAD

**Issue by ghost** [Alexays/Waybar#1053]
Hi!
I am using Waybar 0.9.5 and Wayfire 0.7.
I am having problems with the style of the taskbar module..
The relevant part of the file is:

```
#taskbar button {
	padding: 0 5px;
	background-color: #c18401;
}
#taskbar button.maximized {
	background-color: #50a14f;
}
#taskbar button.minimized {
	background-color: #fafafa;
}
#taskbar button.active {
	background-color: #526eff;
}
```

My intent is to have a white background if the app is minimized, yellow if not minimized, green if maximized and blue if active.

As you can see from the video below, the background of (in this case) Brave, which is a maximized application, some times changes to white..

https://0x0.st/-NLX.mp4

I don't really understand what is going on. Also if I change the order of the CSS (for example swapping maximized and active) i get weird colors, meaning they are not what their relative sections dictates.

**Comment by Alexays** [comment]
@jgmdev @l3nkz Have you ever encountered this problem?

**Comment by l3nkz** [comment]
I haven't encountered the problem myself yet. However, I usually only use the active state. I will have a close look in the code later today.

**Comment by jgmdev** [comment]
> I usually only use the active state.
Same here, I haven´t used maximized/minimized. After adding it for testing I did notice that maximized takes precedence over the active rule if the active css rule is declared before the maximized rule. So even when the window is active the maximized color is shown.

Also if the minimized css rule is declared before the maximized one the maximized will take precedence over the minimized color, meaning that if the window is maximized and then minimized the maximized color is used instead of the minimized one.
