### ISSUE TITLE
Spotify Application Icon not showing; Ignoring Spotify does not work

### ISSUE THREAD

**Issue by uncomfyhalomacro** [Alexays/Waybar#1080]
**OS**
Arch Linux

**Desktop Environment**
Sway: sway 1.6

**Waybar Version**
Waybar v0.9.7-9-g66d8035 (branch 'master')

**Using what feature**
New `ignore-list` for `wlr/taskbar` in configuration

**Expected behavior**
Spotify application icon should be shown when not ignored. It should also be ignored if added in ignored-list.

**Result Behavior**
Screenshots below:
![2021-04-22_22-46_1](https://user-images.githubusercontent.com/66054069/115735515-1fa53800-a3bd-11eb-83e6-4bed940f0d74.png)
![2021-04-22_22-46](https://user-images.githubusercontent.com/66054069/115735530-22a02880-a3bd-11eb-80ce-581a2c6fd26e.png)

**Note**: I reloaded it every time I changed the config.

**Question**: Is this just a spotify issue? If it is then there is nothing I can do about it. There is nothing wrong in the PKGBUILD for spotify in the AUR.

**Comment by ozls** [comment]
I also have this issue. I think it's related to this old bug but I'm not really sure.

https://community.spotify.com/t5/Desktop-Linux/WM-CLASS-window-property-on-Linux/td-p/1247042

It's just an idea, I do not have a solid grip on how apps running in XWayland translate their WM_CLASS properties for Wayland. A few years ago I had similar taskbar issues on XFCE and there are known bug with i3

**Comment by kushraj** [comment]
same issue here, but spotify ultimately set WM_CLASS albeit a bit late. restarting waybar should show the correct icon if this was the issue, its not.

**Comment by ozls** [comment]
That's where my uncertainty lie. This would certainly be the case in a full X session but here Spotify runs on XWayland. When you restart the bar, nothing guarantees that the WM_CLASS of the XWayland windows will be queried again.
And indeed I just checked the "app_id" property of Spotify on Sway (using `swaymsg -t get_tree`) and I get `null`. This doesn't change when restarting Waybar or reloading Sway config for that matter.
So this issue is either a Spotify issue (Why do they still set their WM_CLASS this late ? It's been more than 5 years) or a XWayland issue (Can we force it to query app properties again once they're properly launched?) but I do not think it is a Waybar issue

**Comment by ozls** [comment]
What could be a Waybar problem, however, is the inability to block Spotify from appearing in wlr/taskbar. The app_id of Spotify is `null`, not `"null"`:

```
> swaymsg -t get_tree | grep '"app_id": '

"app_id": "nemo",
"app_id": "code-oss",
"app_id": "firefox",
"app_id": "Alacritty",
"app_id": null,
```

However, neither putting `null`, `"null"` or an empty string in "ignore-list" does anything to prevent the empty icon from appearing. What could we do ?

**Comment by qoheniac** [comment]
But is `"app_id": null` the issue here? I see this for other Flatpak apps as well. For example if I install Zotero from Flathub it also has `"app_id": null` but Waybar shows the correct icon as well as the correct Name entry from the .desktop file. Also the outputs of `swaymsg -t get_tree | jq ".. | objects | select((.name == \"$NAME\"))"`, where `NAME` is either Spotify or Zotero, look very similar.

**Comment by uncomfyhalomacro** [comment]
i think Spotify has got it fixed @qoheniac. I am using the flatpak version. This is the output of lswt. I use riverwm here.
![image](https://user-images.githubusercontent.com/66054069/150498614-86c96fc3-50d8-476e-9fc7-a67129965082.png)

I dunno what Zotero is but imma try to reproduce for your end.

**Comment by uncomfyhalomacro** [comment]
Seems it got fixed @qoheniac. I am using archlinux with riverwm as my tiling window manager.
![Screenshot-0121170823](https://user-images.githubusercontent.com/66054069/150499257-c4704df4-e51d-4ec8-9279-2f14cc67aafd.png)

**Comment by uncomfyhalomacro** [comment]
I can probably close this i think? not sure

**Comment by uncomfyhalomacro** [comment]
Closing as this seems to be the fault of the app or apps if they do not give `app_id` as info. This is beyond Waybar's scope.

**Comment by qoheniac** [comment]
I run Spotify version 1.1.72.439.gc253025e from Flathub with Sway as window manager and it is not fixed for me. Also I think my last reply was maybe a bit ambiguous. I was trying to say that Zotero (also from Flathub) works perfectly fine with Waybar although it also doesn't set `app_id`, so `app_id` doesn't seem to be the issue here. But the way Zotero and Spotify set the information in `swaymsg -t get_tree` looks very similar and as they're both flatpaks the location of their .desktop files and so on is also very similar. I have no clue why it works for one but not for the other as I don't find much of a difference. I think this is worth investigation and perhaps you could reopen the issue.

**Comment by qoheniac** [comment]
As the issue exists even if I start Waybar long after Spotify this is probably unrelated: dasJ/spotifywm#8

But perhaps it's related after all, as I have no clue what's going on.
