### ISSUE TITLE
Tray icons with incorrect size on fractionally scaled output

### ISSUE THREAD

**Issue by minhduc0711** [Alexays/Waybar#1175]
The tray icons on the scaled monitor are weirdly sized on my scaled output
![image](https://user-images.githubusercontent.com/34294427/126855153-7863dbe9-ed3a-4764-8958-df417b6a6640.png)
On my other unscaled output, they appear normally
![image](https://user-images.githubusercontent.com/34294427/126855166-c84d709c-e9d1-4e25-a3db-10b911b38d0d.png)
Could it be related to https://github.com/Alexays/Waybar/pull/1174?

Version: `Waybar v0.9.7-107-g1b4ddbc (branch 'master')`

**Comment by luispabon** [comment]
Having the same problem:

![image](https://user-images.githubusercontent.com/6388823/127145633-065241b6-bcc6-410c-8f18-9687e425893a.png)

the wifi signal icon (nm-applet) is 1/2 the size on a scale 2 display. This is from a recent update.

**Comment by Mathew-D** [comment]
If you go back to before commit https://github.com/Alexays/Waybar/commit/811f0896c9965de2672f03a1fcf673b0781a270d that fixes the error and the icons are the correct size.  Something in that commit breaks the size on some icons.

**Comment by Mathew-D** [comment]
Also it gives this error if you use the master: 
gtk_widget_set_accel_path: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

**Comment by luispabon** [comment]
Reverting to 67d482d fixes it for me as well.

**Comment by Alexays** [comment]
@mswiger can you take a look?

**Comment by minhduc0711** [comment]
There's a small issue left: upon first launching the bar, the icons are way bigger than it should be. They would go back to their normal size if I do something that change the icons' states (e.g. change my ibus input method).
![image](https://user-images.githubusercontent.com/34294427/127799621-53bf1456-bf75-4f03-91e5-cf0810f9ec55.png)

**Comment by mswiger** [comment]
I am able to reproduce the issue that @minhduc0711 is seeing, but only with a multiple-display setup, and it does not reproduce 100% of the time (maybe like 25% of the time for me). It is relatively easy to reproduce by repeatedly reloading the Sway config file until the issue appears ($mod+Shift+c for me).

After spending a bunch of time debugging, this bug seems to behave like some kind of race condition. For tray items that take longer to populate in the tray, this issue never seems to happen. For tray items that populate quickly after waybar is loaded, this problem seems to happen pretty consistently.

From my debugging, when this issue manifests, it appears that the Image widget itself is allocating the wrong amount of space (it will allocate the scaled width/height when it should allocate the unscaled width/height). Not 100% sure how to proceed from here, but I will try to spend some more time on this later this week.

**Comment by mswiger** [comment]
@minhduc0711 I believe that I have a fix for this now: https://github.com/Alexays/Waybar/pull/1211

**Comment by minhduc0711** [comment]
Thank you for the quick fix, the issue is gone on my setup :tada:
