### ISSUE TITLE
error while loading shared libraries: libdate-tz.so.2.4.1:

### ISSUE THREAD

**Issue by minhduc0711** [Alexays/Waybar#1176]
After upgrading to `chrono-date 3.0.1-1`, I am unable to start Waybar
```
waybar: error while loading shared libraries: libdate-tz.so.2.4.1: cannot open shared object file: No such file or directory
```

It works normally if I downgrade to `chrono-date 3.0.0-2`.

Version: `Waybar v0.9.7-107-g1b4ddbc (branch 'master')`

**Comment by KoalaV2** [comment]
+1, experiencing the same issue here. I had to reinstall the waybar-git package from the AUR for it to work again but I belive it'll complain about this if i reboot my laptop.

**Comment by botiapa** [comment]
I have the same issue.

**Comment by Mathew-D** [comment]
I have tried downgrading chrono-date and waybar says it doesn't meet the requirements and I have tried waybar-git with chrono-date 3.0.1-1 and get waybar: error while loading shared libraries: libdate-tz.so.2.4.1: cannot open shared object file: No such file or directory.  I have no idea what to do.

**Comment by niktob560** [comment]
Got a similar issue on ArchLinux with `waybar-git`. Fixed with reinstalling (recompiling) waybar

**Comment by jplatte** [comment]
Unfortunately it seems like the rebuild has to happen *after* that update, so bumping the AUR package version is probably pointless at this point since anybody using waybar will have downgraded that package. I don't think waybar's maintainer(s) can do anything here though, so this issue should probably be closed.
