### ISSUE TITLE
Waybar changing height on window focus change

### ISSUE THREAD

**Issue by varqox** [Alexays/Waybar#1456]
Compare the below images:
![image](https://user-images.githubusercontent.com/4380808/156948229-1999f73a-d4f1-448a-aa16-045f934e0b01.png)
![image](https://user-images.githubusercontent.com/4380808/156948244-f3995632-194a-4583-ac19-536d60deb446.png)
The height of Waybar changes when the focused window changes. It's quite annoying.

This height change happens despite setting `height` to `24` in Waybar's config.

Version: Waybar v0.9.10 (on Arch Linux). I did not notice the above problem with v0.9.9.

**Comment by rieje** [comment]
Experiencing the same thing, also on Arch Linux. Looks like it's related to the [new application icon feature](https://github.com/Alexays/Waybar/pull/1292) because when I focus something that didn't have the icon, the height changes. I don't even see the documentation for this new feature (e.g. how can I disable it to test if it's the culprit?).

Not sure if it's related, but I've also been having issues with the bar occasionally crashing, not updating the sway workspacesfocusing, and the sway title being trimmed to just a few characters. I'm just going to downgrade, this is nearly unusable for me at this state.

**Comment by varqox** [comment]
I dig a little (icon feature was added in bcadf64031ee0520212aa8f092f5ac14122cd924)...
It turns out it can be disabled in the config file by adding `"icon": false,` in the `sway/window` section in config, e.g.
```
{
...
    "sway/window": {
        "icon": false,
    },
...
```

**Comment by quantum5** [comment]
I see the same behaviour and I can reproduce this as soon as I focus on sublime text. `"icon": false` fixes it for me.

**Comment by Alexays** [comment]
Dups of https://github.com/Alexays/Waybar/issues/1461
