### ISSUE TITLE
Workspace 10 shows before 2-9 with sort-by-name

### ISSUE THREAD

**Issue by R0dn3yS** [Alexays/Waybar#1596]
On the "wlr/workspaces" module workspace 10 shows before 2-9 with sort-by-name.

**Comment by CharlesEkkel** [comment]
> Because it reads 1 then 0. So its like Workspace 1, 0 instead of 10. Technically correct. If you want, you can try renaming 10 to 92 or something

I agree, this seems like expected behaviour for sort-by-name. However, personally, I have the same issue yet I still use `sort-by-name` anyway since `sort-by-coordinates` doesn't appear to have any effect (even with `sort-by-name` set to false), and otherwise workspaces are sorted by order of creation (which I assume is sorting by id).

Can anyone confirm if `sort-by-coordinates` actually does anything compared to being turned off?

**Comment by stomar117** [comment]
> Can anyone confirm if `sort-by-coordinates` actually does anything compared to being turned off?

I have tried to manually disable `sort-by-name` and then testing out `sort-by-coordinates`, I can say that it did not yield any difference.

But disabling `sort-by-name` actually fixed the issue with `10` appearing before `1`

This works for me,
```jsonc
    "wlr/workspaces": {
        //"sort-by-coordinates": true, //It did not have an effect
        "sort-by-name": false,
        "on-click": "activate",
        "format": "{name} {icon}",
        "format-icons": {
            "default": "",
            "active": "",
            "urgent": ""
        }
    },
```

**Comment by JoshuaFern** [comment]
Same issue here, 20 workspaces are sorted like:
1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 3, 4, 5, 6, 7, 8, 9

Makes sense why it sorts this way, but it's not how I want my bar to look.
