### ISSUE TITLE
Bluetooth icon invisible until clicked

### ISSUE THREAD

**Issue by always-Z** [Alexays/Waybar#1603]
I am having a minor bug in which on each reboot or restart of waybar the bluetooth icon is not visible until clicked. The space is there, the icon is simply not visible until interacted with.

the bluetooth portion of my config.jsonc is:

```
"bluetooth": {
    "format-on": "",
    "format-disabled": "",
    "on-click": "blueberry",
    "on-click-right": "rfkill toggle bluetooth",
    "tooltip-format": "{status}"
},
```

I am using Manjaro sway with Waybar v0.9.13

**Comment by daangoossens22** [comment]
Maybe ```format-disables``` -> ```format-disabled``` solves it?

**Comment by always-Z** [comment]
Typo in my post not my actual config file. Config file is already spelled "disabled". Edited post to avoid future confusion.

**Comment by daangoossens22** [comment]
I can't seem to reproduce your problem or maybe I'm misunderstanding it.
- Is the problem that the module is entirely empty on restart or does it show some text just not the icons you want there?
- Which icons don't show the "on" or "disabled" icon? Or do they both show just not at restart?
- Do you have to right click or left click to make the icons appear after restart?

**Comment by always-Z** [comment]
- there is no text  so there is just an empty space where the icon should be. also if I hover over it there is no tooltip. Once I click on the blank space a blueberry window will appear as well as the icon. Once the icon shows, the tooltip will show when I hover over it. 

- My system always starts with bluetooth disabled. This reminds me that I had trouble previously with bluetooth always on upon boot and now I can't remember what I did to force it to be disable on boot. If I can remember what I did, I wonder if this could have anything to do with the issue.

- Left click make the icon appear.

 also noticed another oddity. If I toggle bluetooth within the blueberry window the icon does not update until I click on it again. I toggle bluetooth, closed the window, and waited several minutes, but the icon never updated until I clicked on it again. Right click will instantly toggle it with the icon updating as it should.

**Comment by daangoossens22** [comment]
Thanks, I think I know what is happening. The module updates when clicked (that happens I think for all modules when you defined a on-click for it), but the internal update callbacks are not fired. This only happens when it cannot find a bluetooth controller, because almost all functionality depends on that.

- To verify, can you run waybar in the terminal, and check if it outputs the error: ```findCurController() failed: no bluetooth controller found``` (we probably should have checked that first from the beginning, oh well).

This is a bit weird, because it should be able to detect a bluetooth controller otherwise you would not be able to connect or disconnect to devices. Some follow up questions if the above error is printed:

- Does ```systemctl status bluetooth.service``` show any weird errors?
- Does ```bluetoothctl show``` output start with ```Controller ...``` or does it print something else?

**Comment by always-Z** [comment]
Running waybar from terminal does indeed give the exact same no controller found error. 


`systemctl status bluetooth.service`  outputs:

```
○ bluetooth.service - Bluetooth service
     Loaded: loaded (/usr/lib/systemd/system/bluetooth.service; disabled; vendor prem/bluetooth.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
       Docs: man:bluetoothd(8)
```

bluetoothctl show gives no output.

**Comment by daangoossens22** [comment]
That explains alot. bluetooth.service needs to be enabled, otherwise waybar cannot exchange messages via the dbus. I'd recommend running ```systemctl enable --now bluetooth.service``` to enable and start the bluetooth service. If bluetooth is not disabled at startup anymore and you want it to be disabled at startup, I'd recommend putting ```rfkill block bluetooth``` somewhere in a startup script (I think there was also an option for it in the bluetooth config file, but I could be mistaken).

Let me know if this solves the issue.

**Comment by always-Z** [comment]
This did the trick! Icon is now visible upon boot. Also, as an extra FYI I found where I disabled bluetooth on boot. I added `rfkill block bluetooth` to my .profile. I left that in there and now on a fresh boot the icon is visible and disabled and will update immediately when toggled with right click or within blueberry. Thank you!
