### ISSUE TITLE
external widget does not update if & in text

### ISSUE THREAD

**Issue by yorickvP** [Alexays/Waybar#162]
I'm using `playerctl metadata -f '{{emoji(status)}} {{xesam:artist}} - {{xesam:title}}' -F` for a spotify widget. However, when there is an & in the song or artist name, it fails to set this. The tooltip is still correct.

```
Failed to set text ' ▶️ The Whistles & The Bells - Canary Cage' from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape ampersand as &amp;
```

**Comment by Robinhuett** [comment]
I thought I'll have a look at this issue. But we can't just use [`escape_text(const Glib::ustring& text)`](https://github.com/GNOME/glibmm/blob/0cd517399a4fafa6578b63ba45cee8968b317058/glib/src/markup.hg#L110) because it would break the ability to use PangoMarkup.

We could just replace `&` with `&amp;`. But this solution seem pretty dirty to me.
Any suggestions on this?

**Comment by Alexays** [comment]
@yorickvP Did you try to escape the character?

**Comment by Alexays** [comment]
Now you can escape the script output by setting `escape` to `true`

**Comment by yorickvP** [comment]
Thanks!
