### ISSUE TITLE
[wlr/taskbar]  "all-outputs" : false   not work

### ISSUE THREAD

**Issue by xaotag** [Alexays/Waybar#1633]
![image](https://user-images.githubusercontent.com/40427877/180701792-51dbf32f-92a6-4ddf-8f09-b1872e19f0df.png)

**Comment by RobertMueller2** [comment]
OK, this is a fairly old issue. If you still encounter the issue with a recent Waybar commit, could you kindly explain which behaviour you see and which behaviour you expect?

I can not reproduce any issue with all-outputs set to either true or false, it's behaving like I would expect it to as per the manpage. But it's possible that it was fixed in the last 2 years. ;)
