### ISSUE TITLE
[bug] battery level is wrong

### ISSUE THREAD

**Issue by aryklein** [Alexays/Waybar#1843]
After upgrading Waybar to version 0.9.16-1 in Archlinux, it shows 30% capacity when it is actually 58%.
Executing `upower -i /org/freedesktop/UPower/devices/battery_BAT0 ` or `cat /sys/class/power_supply/BAT0/capacity ` the capacity showed is 58%.
Downgrading to version `0.9.15-2` solves the issue.

**Comment by Alexays** [comment]
@grfrederic any ideas?

**Comment by grfrederic** [comment]
yes, the issue is known and I already posted a l fix on my original PR (#1788), but no one affected had the time to check if it will work.

**Comment by grfrederic** [comment]
yes, the issue is known and I already posted a l fix on my original PR (#1788), but no one affected had the time to check if it works for them.

**Comment by ipochi** [comment]
I am facing the same, for me its because there are two batteries shown by the system

```

❯ upower -e

/org/freedesktop/UPower/devices/battery_BAT0
/org/freedesktop/UPower/devices/battery_wacom_battery_0
```

**Comment by moofter** [comment]
I have the same issue. Both ```acpi``` and ```upower``` commands show the correct charge level but the battery module shows something else. When it's 100% charged the battery module thinks it's only 75% and when discharging/charging the discrepancy is about 10-20% as well.

Would it be possible to setup a custom entry that uses the output of a console command as temporary work-around until this issue is solved?

The correct charge level is shown in btop, I'm not sure if it's helpful but maybe how btop does it can be somehow used to fix this issue?

https://github.com/aristocratos/btop/blob/main/src/linux/btop_collect.cpp#L531-L666

I'm not a programmer, just someone who spend more time than I want to admit trying to get the battery charge level to display correctly 😅

So I'm not sure if it's feasible to port/implement btop's method. I ended up comparing a working method to how the battery module does it hoping it would help me fix the issue but it didn't. But I wanted to share it here as it might be useful to someone else.

**Comment by zearp** [comment]
Also ran into this setting up my first way bar install. A temporary fix is to use ```full-at``` and set it to whatever percentage of the design capacity reported by ```acpi -V``` is left. I noticed some other apps like Neofetch will also show the remaining design capacity as current charge level. A more elegant fix would be that the battery module takes remaining capacity into account so you don't have to keep on updating the ```full-at``` value while the battery wears out.

https://github.com/Alexays/Waybar/wiki/Module:-Battery
