### ISSUE TITLE
window label is shown when no window is focused in Hyprland module

### ISSUE THREAD

**Issue by fybx** [Alexays/Waybar#1934]
> Did you have a look at #1448 or #1349?
> 
> I think you could style
> ```
> window#waybar.empty #window {  
>  background:none;  
> }  
> ```
> or similar.
_Originally posted by @RobertMueller2 in https://github.com/Alexays/Waybar/issues/1507#issuecomment-1090619823_
      

This solution for Sway doesn't work for Hyprland/window module.

**Comment by RobertMueller2** [comment]
Not much idea of the hyprland/window module, but replying here because I was tagged. ;) I think you can stop trying around with CSS at this point. ;) In general, it can be helpful to use GTK_DEBUG=interactive environment variable with a test config to get an insight to CSS names and classes. Here is a comparison between hyprland/window and sway/window modules:

![swappy-20230112_061506](https://user-images.githubusercontent.com/29629287/211983740-293af1a9-a156-4aa7-a6e0-13183119f90a.png)

sway/window adds CSS classes to the parent GTK Window with the name waybar (window#waybar), which you can use to style the GTK Label with the name window.  hyprland/window doesn't do any of this.

Now whether it SHOULD, or whether it should do things the same way, I can't say. ;)

**Comment by fybx** [comment]
In Hyprland, the label element gets the ID `#window`, but classes do not reflect state changes as it does on Sway.

![20230112_21h33m58s_grim](https://user-images.githubusercontent.com/41127439/212150307-f1f37b05-d51a-442d-a297-09c20b3f35db.png)

Maybe an update regarding this will solve it, thanks for responding :)
