### ISSUE TITLE
CPU temp not reading correctly

### ISSUE THREAD

**Issue by zlehnherr1** [Alexays/Waybar#1943]
Not sure why, but my CPU temp is reported as 65273 C, how do I fix this?
OS: Garuda
Device: Intel Nuc

**Comment by spikespaz** [comment]
You need to manually specify some paths to the proper device node to read from. I haven't quite figured out how to get a static path (that persists reboots) myself, so I don't want to try to help too much. Read the wiki page again and play with temperature zone and the hwinfo paths.

**Comment by spikespaz** [comment]
Made progress, now where @zlehnherr1 is.

Steps taken:
```
$ lspci -v
<redacted for brevity>
00:18.3 Host bridge: Advanced Micro Devices, Inc. [AMD] Renoir Device 24: Function 3
	Flags: fast devsel, IOMMU group 11
	Kernel driver in use: k10temp
	Kernel modules: k10temp
<redacted for brevity>
```
Notice there is a device with the `k10temp` driver, look it up, discover it is a sensor integrated into the processor die.

Make sure this path exists: `/sys/devices/pci0000:00/0000:00:18.3/hwmon`

It does, take a sample reading:
```
$ cat /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon5/temp1_input
58875
```

That looks wrong, but I don't know the unit so I try it anyway:
```
      temperature = {
        hwmon-path-abs = "/sys/devices/pci0000:00/0000:00:18.3/hwmon";
        input-filename = "temp1_input";
        critical-threshold = 30;
        format = "{icon} {temperatureC}°C";
        format-critical = "󰸁 {temperatureC}°C";
        format-icons = ["󱃃" "󰔏" "󱃂"];
      };
```

Restart Waybar, temperature reading 59°C. Determine the unit inside `temp1_input` is thousandths of a degree Celsius.
Still looks wrong, even knowing the unit. Look up `k10temp` again, read the description, find this excerpt:

>  Tctl is the processor temperature control value, used by the platform to
> control cooling systems. Tctl is a non-physical temperature on an
> arbitrary scale measured in degrees. It does _not_ represent an actual
> physical temperature like die or case temperature. Instead, it specifies
> the processor temperature relative to the point at which the system must
> supply the maximum cooling for the processor's specified maximum case
> temperature and maximum thermal power dissipation.

I'm annoyed. Looks like we need to do some math here to find the correct physical temperature, and that has to happen inside Waybar's source code. The format string syntax we're given doesn't have library functions or support expressions necessary.

Would also be super super cool if one of the thousands of people who have figured this out before could have been bothered to write it down.

**Comment by spikespaz** [comment]
Upon further research, the temperature shown by `k10temp` is the actual junction temperature, and is therefore more accurate than package sensors. Please tell me if I'm wrong.

Pending further information, I'm sticking with it, and raising my critical temperature to 100C per AMD's specifications for the Tjmax: <https://www.amd.com/en/product/9686>

**Comment by Erothas** [comment]
So, I just had this issue today. As I was looking for solutions, I stumbled across this page. I would like to provide the solution I found in case it helps anyone.

You basically start out with pinpointing which file is the `k10temp` monitor. You can check that with a `bat /sys/class/hwmon/hwmon*/name`. For me, k10temp was in hwmon3. Waybar's config file had its temperature module reading hwmon2 file. So, all I did was point it towards the `/sys/class/hwmon/hwmon3/temp1_input` file instead.

**Comment by Darc-Charlie** [comment]
I just ran into this issue after upgrading my Arch system. 
Looking at the logs after running `sway -d`, I see multiple entries for: `[error] temperature: argument not found` and after stumbling upon this open issue, I tried investigating my hwmon-path which was set to `/sys/class/hwmon/hwmon2/temp1_input`.

 Based on @Erothas input above, I looked through all my temp1_input readings and discovered that `cat /sys/class/hwmon/hwmon2/temp1_input` and `cat /sys/class/hwmon/hwmon3/temp1_input` were returning negative integers as opposed to `cat /sys/class/hwmon/hwmon4/temp1_input`. I don't know why this is the case, but when I updated my waybar config to use hwmon4, my temp readings went back to its normal two-digit readings.
 
It's also good to note that due to my previously large temperature readings exceeding my set critical-threshold of 90, the reading of the temperature in the waybar didn't display at all and just flashed red.

**Comment by spikespaz** [comment]
`hwmon/hwmon*` paths are not static and have the potential to change across reboots. Perhaps `udev` can provide a solution.

This might work to create a link to the `hwmon*` path in `/dev`:
```
KERNEL=="hwmon*", SUBSYSTEM=="hwmon", ATTR{name}=="<sensor_name>", SYMLINK+="hwmon/<link_name>"
```

This is off the top of my head and untested.

**Comment by Darc-Charlie** [comment]
I still haven't figured out the strange temperature readings from my sensors, but I've discovered a workaround. This is the output of the `sensors -u` command:

```➜  ~ sensors -u
soc_dts1-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: -59.910

coretemp-isa-0000
Adapter: ISA adapter
Core 0:
  temp2_input: 35.000
  temp2_max: 90.000
  temp2_crit: 90.000
  temp2_crit_alarm: 0.000
Core 1:
  temp3_input: 35.000
  temp3_max: 90.000
  temp3_crit: 90.000
  temp3_crit_alarm: 0.000
Core 2:
  temp4_input: 33.000
  temp4_max: 90.000
  temp4_crit: 90.000
  temp4_crit_alarm: 0.000
Core 3:
  temp5_input: 33.000
  temp5_max: 90.000
  temp5_crit: 90.000
  temp5_crit_alarm: 0.000

iwlwifi_1-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: 30.000

soc_dts0-virtual-0
Adapter: Virtual device
temp1:
  temp1_input: -59.910

BAT0-acpi-0
Adapter: ACPI interface
in0:
  in0_input: 12.413
curr1:
  curr1_input: 0.264
```

As you can see, my soc_dts0-virtual-0 and soc_dts1-virtual-0 sensors report negative temperatures, so my workaround was to use one of my CPU core temperature readings instead. But the issue @spikespaz mentioned previously became an issue. Every so often, my waybar temperature reading would disappear on boot due to the hwmon path for my core temp input changing. I was eventually able to dig this solution up: [[SOLVED] How to make persistent hwmon to get cpu temperature](https://bbs.archlinux.org/viewtopic.php?id=282319).  I followed the solution, removed the `thermal-zone` and `hwmon-path` in my existing config, and replaced them with `hwmon-path-abs` and `input-filename`. My waybar config section for temperature now looks like this:

```
    	"temperature": {
    		...
		"hwmon-path-abs": "/sys/devices/platform/coretemp.0/hwmon",
		"input-filename": "temp2_input",
    		...
    	},
```

So far, I've gone three boots without my temperature reading disappearing. I hope this helps.
