### ISSUE TITLE
Add rounded power draw to battery module

### ISSUE THREAD

**Issue by cloudlena** [Alexays/Waybar#2013]
When using `{power}` in the battery module, it currently shows a very precise value (`13.81161` in my case). Since this number is not updated in real time anyway, I would argue that such precision doesn't make sense and only makes things less legible. 

What do people think of the following three proposals? I think, implementing one of them would make sense and would personally prefer the first one, but would be just as happy with either of them.

- Round the output of `{power}` to an integer (or maybe a float with 1 digit after the comma)
- Add a `{roundedPower}` tooltip format that shows the value rounded to an integer
- Add a new property to the config (e.g., `format-power-precision`) that is an int which describes how many digits after the comma the power should be displayed with

**Comment by NomisIV** [comment]
I don't think it makes sense to implement this, since these formatting options are already provided in the fmt library. Read more about it [here](https://github.com/Alexays/Waybar/wiki/FAQ#how-can-i-prevent-modules-from-changing-size-aka-fixed-width-modules-and-monospace-fonts) and [here](https://fmt.dev/latest/syntax.html)

**Comment by cloudlena** [comment]
That's exactly what I was looking for. Thanks, @NomisIV and sorry, I didn't find that myself!
