### ISSUE TITLE
sway/workspaces: Focused and default icons not displayed

### ISSUE THREAD

**Issue by d4rios** [Alexays/Waybar#2188]
Hi

In my waybar configuration, the module "sway/workspaces" does not show the **focused** workspace and **default** workspace **icons**. I have only been able to change the color of the workspace used, using the style.css file. Otherwise it would be very difficult for me to know which workspace I am in.

Does anyone know why this might be happening?. 

❯ sway -v
sway version 1.8.1

❯ waybar -v
Waybar v0.9.17

sway/workspaces module config:

    "sway/workspaces": {
        "all-outputs": true,
        "disable-scroll": true,
        "format": "{icon}",
        "format-icons": {
        "1": "",
        "2": "",
        "3": "",
        "4": "",
        "5": "",
        "6": "",
        "7": "",
        "8": "",
        "9": "",
        "10": "",
        "urgent": "",
        "focused": "",
        "default": ""
        },

        "persistent_workspaces": {
        "1": [],
        "2": [],
        "3": [],
        "4": [],
        "5": [],
        "6": [],
        "7": [],
        "8": [],
        "9": [],
        "10": []
        }
 },

[My Waybar](https://tinypic.host/images/2023/05/25/Screenshot_2023-05-25-07-35-23_1920x10800A1920x1080.png)

**Comment by Anakael** [comment]
Default icon doesn't work because you have config for all 10 workspaces. Just try to remove some numbered workspaces from "format-icons" section and it should be fine.

**Comment by Anakael** [comment]
And the same reason for missing `focused` icon. You can reproduce it by:
1) remove some numbered workspaces from config (for example, starting from 5)
2) create workspace 6 and launch terminal on it
3) create workspace 7 and stay on it
Then you will have 6-default and 7-focused.
For `focused` icon behavior it is definitely a bug. It should have priority over existing configs.

**Comment by d4rios** [comment]
Thanks for your answer, Anakael.

Now the waybar shows me the default icon in the last workspace also shows 6 workspaces when I only have 5 defined. 
I don't understand anything.

sway_output
![imagen](https://github.com/Alexays/Waybar/assets/80931135/a4571d34-d7af-4378-a91f-081579fb9841)

sway/workspaces
![imagen](https://github.com/Alexays/Waybar/assets/80931135/b442295a-97f2-4bc4-8e0a-f2e5d798812a)

waybar
![imagen](https://github.com/Alexays/Waybar/assets/80931135/92fcf544-90dd-4423-ac2b-799827da7aa7)

**Comment by Anakael** [comment]
You have configs for 1-5 workspaces. Their icons are taken from numbered config. For workspace 6 it is taken from "default".
The fact that for 1 workspace icon isn't taken from "focused" config is bug. I'll try to fix it in near future.

**Comment by Anakael** [comment]
focused icon should always have higher priority before named icon.
-> And if I were inside workspace 1 it did show the Firefox icon (which I still want it to show)
It should show focused now. 
->  overwrites the actual icon
This is not right.
I'll check it out again.

-> I think what we really need is a individual focused field for every workspace.
Can you provide some usecases? For me it's seems very strange.

**Comment by Samu1808** [comment]
The behaviour before was:
- named workspaces shown their custom icons even if they are focused
- workspaces which are not named had the default icon and switched to the focused icon if focused
    -  which pretty made sense to me because for my config you had the non filled dot for defaults and the filled dot for focused defaults

The behaviour now is:
- named workspaces have their custom item if unfocused and the focused item if focused
- this doesnt make too much sense because I want to see the custom icon that I set for my named workspace if its focused or not
   - you can see if its focused by colored accent and the bar on top the icon anyways
- and if I dont define a focused icon (to get my old behaviour back) it works for named workspaces, but for focused default workspaces there is no icon displayed
    - this is the proof for me that its not intended what you did by just changing the displaying order but that the old behaviour was much better

Now to the "problem" discussed here and alternative solutions:
- in my opinion @d4rios does something which was not really intended to do
- defining 5 named workspaces all with the same (default) icon and then want to use the focused icon if they are focused
   - that makes sense for his config but not for mine
   - as I said I dont want to see the filled circle if I am in workspace 1, I still want to see my Firefox logo
- but if you want to solve @d4rios problem the better solution is to provide the ability to give each named workspace their own focused icon
    -  so that one can define a focused item for each named workspace and one for default workspaces
    - I think it makes things better and more customizable and would be a enhancement anyways

**Comment by kira-bruneau** [comment]
@Anakael How was the old behaviour a bug? I'd expect icons that apply to a specific workspace to take precedence over icons that apply to any workspace.

Like @Samu1808 mentioned, when you're only using icons, having focused & urgent icons prioritized over workspace-specific icons makes it unclear what specific workspace is actually focused / needs attention.

I can see why @d4rios wants the new behaviour for their use-case, but #2223 broke a bunch of other people's existing single-icon configs.

**Comment by Alexays** [comment]
> 2\. Additional section to config. Something like "high-priority-named: [ "1:web" ]", which applies the same logic as in p.1.

I would prefer this option.

**Comment by Anakael** [comment]
> @Anakael Why was the old behaviour considered a bug? 

Because it works the way it wasn't intended to work. wlr/workspaces works the same way.

> I'd expect icons that apply to a specific workspace to take precedence over icons that apply to any workspace.

focused/urgent icons should be selected by **state** of workspace. In old behavior they was **never** selected in specific icons setups so was useless.

> Like @Samu1808 mentioned, when you're only using icons, having focused & urgent icons prioritized over workspace-specific icons makes it unclear what specific workspace is actually focused / needs attention.

In old behavior you just never see these icons.

> I can see why @d4rios wants the new behaviour for their use-case, but #2223 broke a bunch of other people's existing icon-only configs.

It didn't break. It just start to work for such configs.

**Comment by Anakael** [comment]
@Samu1808 
Now you can use high-priority-named option for your use-case.

**Comment by Samu1808** [comment]
thank you very much <3
