### ISSUE TITLE
[Feature Request] hyprland/workspaces

### ISSUE THREAD

**Issue by Anakael** [Alexays/Waybar#2194]
Is there any current acitivites about implementation of worspaces module for Hyprland?
If no, I'd like to start ones :)

**Comment by theshatterstone** [comment]
Currently, you can use wlr/workspaces. It's in the experimental stage, but I think if that was taken as a base, with all the unnecessary components removed, and extra features like the [hyprctl](https://aur.archlinux.org/cgit/aur.git/tree/hyprctl.patch?h=waybar-hyprland-git) patch used by [waybar-hyprland-git](https://aur.archlinux.org/packages/waybar-hyprland-git)

**Comment by Anakael** [comment]
-> you can use wlr/workspaces
Yes, and I do every day :)
But, there are some cathes:
1) It requires to build waybar with experimental flag locally instead of just pulling actual stable version from repo (not AUR)
2) wlr_workspaces protocol is still in merge request for 2 years already (https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/40) and honestly I've already started to lose hope that MR will be merged.

About patch that was mentioned: it's just nonsense IMO. That should be fixed in Hyprland protocol implementation.
I think I'll started with it.

**Comment by theshatterstone** [comment]
Well, I certainly agree with all of what you said. I would love to see hyplrand/workspaces module that incorporates these features, and I'm not sure if you would be able to get this to be fixed over on Hyprland, which is why I think this patch (which I agree is nonsense and shouldn't even have a reason to exist in the first place) is, unfortunately, the best solution we currently have, to get clickable workspaces on Hyprland. And, of course, I would love for this module to not require experimental, because having to build from source is kinda painful for me. 

And don't even get me started on the AUR packages (they haven't been touched since April). The only thing they're good for is to be used to rebuild Waybar locally, but they aren't even really necessary for that. To anyone reading this, please do NOT use these packages, as they are severely outdated. (I'm not sure if they even have the wireplumber fix)

**Comment by Anakael** [comment]
-> the best solution we currently have, to get clickable workspaces on Hyprland
Actually, click on workspace works fine for me without any patches. Maybe it was just fixed on Hyperland.

**Comment by zjeffer** [comment]
> And don't even get me started on the AUR packages (they haven't been touched since April). The only thing they're good for is to be used to rebuild Waybar locally, but they aren't even really necessary for that. To anyone reading this, please do NOT use these packages, as they are severely outdated. (I'm not sure if they even have the wireplumber fix)

@theshatterstone If you use waybar-git or waybar-hyprland-git, they should autoupdate to the latest git version, right? These are updated automatically.
