### ISSUE TITLE
[Feature request] Scrolling text

### ISSUE THREAD

**Issue by ShellTux** [Alexays/Waybar#2233]
So the basic idea of this feature, is whenever some text is larger than the module width, the text would be scrolling from the left or from the right.

Like this:
![scroll](https://hosting.photobucket.com/albums/z454/MotiveWeight/Never-Give-Up.gif)

I know, that you can limit the length of the given text for a module, but I think, this would be a nice feature for the `mpd` module.

Some considerations:
- would this feature be intensive on the cpu?
- would it be much effort to implement this?

I would love to hear feedback about this feature.

**Comment by RobertMueller2** [comment]
Right now, the "heavy" lifting of the max-length config is done by `Gtk::Label` and its method `set_max_width_chars`. 

I'd say it's tricky to implement a marquee function in `ALabel`, because the event control for any updates and re-rendering is in the places that use `ALabel` and not in `ALabel` itself. (But perhaps I understood that wrong from a quick glance.)

What might work though in the long run, is to use CSS. In general, it's possible to create Marquee animation using CSS like this:

```
#custom-xyz {
    animation-name: marquee;
    animation-duration: 5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-play-state: running;
    background-color: #330000;
    color: #ffffff;
}

@keyframes marquee {
    0%{ 
	transform: translateX(0px);
    }
    100% {
        transform: translateX(100px);
    }
}
```

Sadly, this does not work in Gtk3, but might to a certain degree in Gtk4, if Waybar ever switches to that.

I had ChatGPT create [this python demo](https://gist.github.com/RobertMueller2/c70c3c997324f7f913b6d16232911a30#file-gtk4-marque-example-py). Gtk does not accept percentages as parameter to translateX at this point, perhaps that needs a feature request as well.

There are probably plenty examples out there for "CSS Marquee" that could be tried.
