### ISSUE TITLE
UPower always montiors the battery if the native-path doesn't exist

### ISSUE THREAD

**Issue by ribosomerocker** [Alexays/Waybar#2263]
I have enabled the module and specifically enabled `hide-if-empty = true;` on NixOS. I specified a directory that wasn't always on-- only when connected to the device via  bluetooth, but it seems for UPower if it detects that it's empty, it switches to my laptop's battery no matter what.

**Comment by StayPirate** [comment]
The same happen to me. If you enable the `tooltip`, you can probably see that even though you defined a specific device via `native-path` the upower module shows all connected devices anyway.

My configuration (for my Bose QC35 headset)
```json
	"upower#boseqc35": {
		"native-path": "/org/bluez/hci0/dev_04_52_C7_7E_67_82",
		"show-icon": false,
		"icon-size": 20,
		"hide-if-empty": true,
		"format": " {percentage}",
		"format-alt": " {percentage}",
		"tooltip": true,
		"tooltip-spacing": 5,
		"on-click": false
	},
```

The way it is shown in waybar (with the correct battery level value of the correct tracked device)

![image](https://github.com/Alexays/Waybar/assets/37073343/9514ca49-f6ec-4378-9617-0f380f9064cf)

The tooltip I see when I mouse-over it.

![image](https://github.com/Alexays/Waybar/assets/37073343/95c8cd66-4b45-4215-bcfd-d208ef931f43)

Since I configured the module to only track the headset, I would not expect to see my mouse battery level listed too. Am I wrong?

I think having multiple device listed there, may trick the module to consider the device still connected even when I turn off my headset. Does something similar happen to you as well?

**Comment by StayPirate** [comment]
By giving a closer look at [the documentation](https://github.com/Alexays/Waybar/wiki/Module%3A-UPower) `hide-if-empty` is described as 

> Defines visibility of the module if **no devices** can be found.

Hence, if at least one valid device is connected, the module is shown in waybar, even when the tracked devices is disconnected but another valid device is still connected.

https://github.com/Alexays/Waybar/blob/2c927de4c624d0c560f73ad78b4abc85fb703562/src/modules/upower/upower.cpp#L341-L342

`devices.size() == 0` sounds to me like if there's at least one valid-connected device.

Here the definition of valid device:
https://github.com/Alexays/Waybar/blob/2c927de4c624d0c560f73ad78b4abc85fb703562/src/modules/upower/upower.cpp#L322-L326

**Comment by ribosomerocker** [comment]
Closing in favor of your issue since I don't use Waybar right now.
