### ISSUE TITLE
Hyprland/window.empty not working

### ISSUE THREAD

**Issue by Faervan** [Alexays/Waybar#2765]
I did:
```
#window {
    background-color: rgba(0,0,0,0.4);
    border-radius: 10px;
    padding: 0 10px 0 5px;
}

#window.empty {
    background-color: transparent;
}
```
in ~/.config/waybar/style.css to hide the window module if there is no window in the current workspace, as described in the [Wiki](https://github.com/Alexays/Waybar/wiki/Module:-Hyprland#style-1), but my `background-color: transparent;` doesn't appear to have any affects:

![satty-20231223-18:07:13](https://github.com/Alexays/Waybar/assets/124069539/d66de423-8cd2-46c5-bc5b-3e17a7ca79c5)
![satty-20231223-18:07:44](https://github.com/Alexays/Waybar/assets/124069539/6679d507-cf03-49dc-87bf-1b8a168149a2)

Am I missing something or is this a bug?

**Comment by RobertMueller2** [comment]
Have you tried using `window#waybar.empty #window` instead of `#window.empty`?

I know the wiki says otherwise, but looking at the source (git master, commit d2767fb84ac2efed1c29313dec7ede1b756a6f81), I'd say the additional classes such as empty, floating, solo etc area only ever applied to the main waybar window (element type GtkWindow, in CSS: "window", with id "#waybar") rather than the window module (element type I think GtkLabel, in CSS: "label" with id "#window").

Either this is indeed a bug, or the wiki page is not up-to-date with the code.

I'll add it's unfortunate that we have Waybar as CSS type "window", which afaik can't really be done differently, and then the various window modules again having the id "window". But then the modules apply their classes not to the window module element itself, but rather the Waybar, of course for practical reasons, but that makes it confusing. Unfortunately, doing it differently now would be a breaking change for many existing configs.

**Comment by Faervan** [comment]
> Have you tried using `window#waybar.empty #window` instead of `#window.empty`?

That solved it. Thanks!
