### ISSUE TITLE
`mpd_status_get_state` segfaults on null `state_.get()`

### ISSUE THREAD

**Issue by cole-h** [Alexays/Waybar#277]
From my last comment at #273:

---

Update on the `mpd_status_get_state` segfault: it occurs due to `state_.get()` occasionally being `nullptr`. I don't know of a nice way to handle this because my rudimentary modifications (just checking `if (state_.get() != nullptr)` before get state) would update the module to say "Disconnected", but wouldn't ever refresh state. Just `mpd: Connection to MPD closed` in the logs.

First thing we probably want to look at is why `tryConnect()` doesn't connect after this occurs, and the `connection_.reset()` and `alternate_connection_.reset()` lines don't help in `checkErrors()`. I have 0 experience with threaded programs in this regard.

## STR (on my system, at least)

1. Start up the bar
2. Play music for a second or two
3. Pause it
4. Do something for a minute ~~or so~~ (for me, always happens after 1 minute, exactly: `mpc pause;sleep 60;mpc play`)
5. Play music again
6. Observe segfault

N.B. Everywhere else that uses `state_.get()` has a chance to segfault -- I saw a few in the `elapsedTime` and `totalTime` variables, as well as the icons just below that while messing around.

cc: @minijackson @Alexays

**Comment by minijackson** [comment]
So I've had a bit of time to look at it, and it appears that when the connection "times out", the operation to block on events never stops to block :-/

Because it's that thread that tries to reconnect when the connection drops, the module will stay disconnected…

I think three solutions are possible:
- Find a way to "unblock" the event listener
- Add a timeout to the event listener (will make the module update more frequently but I don't think this is a big deal)
- Change everything
