### ISSUE TITLE
Hyprland: Special workspace switching is wonky

### ISSUE THREAD

**Issue by Ben9986** [Alexays/Waybar#2861]
I have hyprland/workspaces module loaded in waybar and i have noticed that if i open an empty special workspace and then close it again, the regular workspace with the same number is removed from waybar.

**Steps to reproduce:**
Have hyprland/workspaces loaded into waybar
On workspace 1, open workspace `special:1` using a defined key bind. 
Close that special workspace with no windows on it.
Notice that the waybar workspaces module is now missing workspace 1. 

I have repro'd this issue after running `socat - UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock` and got this output: 
```
createworkspace>>special:1
activewindow>>,
activewindowv2>>,
activespecial>>special:1,HDMI-A-1
activespecial>>,HDMI-A-1
activewindow>>kitty,nix-shell -p socat
activewindowv2>>3a2f8c0
destroyworkspace>>special:1
```

To me (not a programmer), it looks like it's because the hyprland socket doesn't report that workspace 1 is focused again after the special is closed. Only reporting the focused window, in my case kitty.
I initially thought this was a hyprland issue but after the above steps, switching between regular workspaces never brings back the one that "disappeared" on waybar despite hyprland correctly reporting the workspace switch.

Hope this made sense, if you need any more info/testing I'm happy to help!

**Comment by zjeffer** [comment]
This is probably caused by this: https://github.com/Alexays/Waybar/pull/2540

@Syndelis

**Comment by Syndelis** [comment]
Hey there! It's a combination of problems: originally, some Hyprland IPC messages would purposefully *not* include the `special:` prefix, which brought previous work on Waybar to strip the prefix at first. This did cause some code not to correctly account for worksace "specialness" when comparing names, including the linked PR.

I'm working on a solution in #2864. Although the first commit already addresses this problem, I'm thinking of implementing a wrapper type for the name attribute so that you can't compare *just* names (think of Rust enums). I'll see where that gets me.

For the time, could you please try that PR, @Jaques22 ?

**Comment by Jaques22** [comment]
Amazing thanks that PR fixes the issues i was having. Special workspaces now show up like i'd expect. 
Only thing i have noticed is that if i am on workspace 1 and open special:1 then i have two "1"s highlighted in my bar which i guess is technically correct? Though it would be nice to have the option of "special workspace focus overrides regular workspace" if possible but not sure its in the scope of this issue.

**Comment by Syndelis** [comment]
> Amazing thanks that PR fixes the issues i was having. Special workspaces now show up like i'd expect. 
> Only thing i have noticed is that if i am on workspace 1 and open special:1 then i have two "1"s highlighted in my bar which i guess is technically correct? Though it would be nice to have the option of "special workspace focus overrides regular workspace" if possible but not sure its in the scope of this issue. 

Oh that's not a problem caused specifically because your special and regular workspaces share the same name, that's just a thing in waybar. If I'm not mistaken either Hyprland doesn't notify when the special is toggled or we are not listening to the right event (can't remember). I'll check later to see which is it and, if the latter, I'll implement it

**Comment by yavorski** [comment]
Switching between two empty workspaces fast, causes undesired glitch effect, because the both of them are visible for a short time, until the one is cleared. Note this does not happen under sway, only in hyprland.

**Comment by Ben9986** [comment]
> Switching between two empty workspaces fast, causes undesired glitch effect, because the both of them are visible for a short time, until the one is cleared. Note this does not happen under sway, only in hyprland.

This sounds like a completely different issue. I'd open a separate bug report if I were you. 
I'm going to close this issue as the original bug is actually fixed already.

**Comment by zjeffer** [comment]
> Switching between two empty workspaces fast, causes undesired glitch effect, because the both of them are visible for a short time, until the one is cleared. Note this does not happen under sway, only in hyprland.

You're probably encountering this issue: https://github.com/Alexays/Waybar/issues/2484
