### ISSUE TITLE
RFE: please port to `wireplumber-0.5`

### ISSUE THREAD

**Issue by kloczek** [Alexays/Waybar#2904]
Any plans to do that soon? 🤔

**Comment by Alexays** [comment]
Tracked here https://github.com/Alexays/Waybar/pull/2919

**Comment by alebastr** [comment]
The problem is, there's no `wireplumber-0.5` yet.
The [release notes for previews](https://pipewire.pages.freedesktop.org/wireplumber/resources/releases.html#wireplumber-0-4-82) clearly state that the API for 0.5 is not stabilized, and 0.4.81..0.4.82 already contains breaking changes. Any porting work is premature until it's clear that the new API is stable.

**Comment by FilippoBonazziSUSE** [comment]
wireplumber upstream has stated that there are "no planned API/ABI changes during RCs" (with 0.4.90 being RC1), so it should be safe to start upgrading the code to the 0.5 API now.

**Comment by FilippoBonazziSUSE** [comment]
0.5.0 has been [released](https://pipewire.pages.freedesktop.org/wireplumber/resources/releases.html#wireplumber-0-5-0)
