### ISSUE TITLE
does not yet support wireplumber 0.5, suboptimal for arch

### ISSUE THREAD

**Issue by YjzJim** [Alexays/Waybar#3059]

**Comment by flaxplax** [comment]
There is a PR, hopefully it will be sorted soon
https://github.com/Alexays/Waybar/pull/2919

**Comment by jefrecantuledesma** [comment]
I'm sure you're already doing this, but, in the meantime, the Puleaudio module is working just fine for me. Glad to see it's an issue that's known, though.

**Comment by enk-it** [comment]
Facing this too.
Can't even start Waybar

**Comment by flaxplax** [comment]
@enk-it you can change wireplumber module to pulseaudio and it will start, or you can downgrade wireplumber to the previous version

**Comment by CaptialState** [comment]
`sudo pacman -U https://archive.archlinux.org/packages/w/wireplumber/wireplumber-0.4.17-1-x86_64.pkg.tar.zst https://archive.archlinux.org/packages/l/libwireplumber/libwireplumber-0.4.17-1-x86_64.pkg.tar.zst`

Ended up having to downgrade it, For now it thankfully didn't mess up anything else

**Comment by enk-it** [comment]
Thanks @flaxplax  and @CaptialState. Downgrading wireplumber did the trick

**Comment by KikoJC** [comment]
Hello. I was having the same problem (almost) except the file I was missing was `libwireplumber-0.4.so.0`. Arch upgraded that to libwireplumber-5. Instead of downgrading anything, I thought that I would try to see if my waybar was up to date. I was using waybar-git from the AUR repo, so I did `sudo pacman -S waybar` and that did the trick. It removed the waybar-git package and installed the waybar from the main arch repos. That fixed it. Thought I write it here in case it helps anyone.

**Comment by CaptialState** [comment]
https://gitlab.archlinux.org/archlinux/packaging/packages/waybar/-/blob/main/0001-Update-Wireplumber-API-to-0.5.patch?ref_type=heads

I was digging around and i found this, It seems to be a patch that updates wireplumber api to 0.5??

**Comment by CaptialState** [comment]
UPDATE: Modifying the PKGBUILD from aur's [waybar-git](https://aur.archlinux.org/packages/waybar-git) seems to work

**Comment by Alexays** [comment]
Fixed with latest master version
