### ISSUE TITLE
[issue]: clock seconds is not live

### ISSUE THREAD

**Issue by its-19818942118** [Alexays/Waybar#3085]
```
 "clock": {
        "format": "{:%H:%M:%OS}",
        "rotate": ${r_deg},
        "interval": 1,
        "format-alt": "{:%R 󰃭 %d·%m·%y}",
        "tooltip-format": "<tt>{calendar}</tt>",
        "calendar": {
            "mode": "month",
            "mode-mon-col": 3,
            "on-scroll": 1,
            "on-click-right": "mode",
            "format": {
                "months": "<span color='#ffead3'><b>{}</b></span>",
                "weekdays": "<span color='#ffcc66'><b>{}</b></span>",
                "today": "<span color='#ff6699'><b>{}</b></span>"
            }
        },
        "actions": {
            "on-click-right": "mode",
            "on-click-forward": "tz_up",
            "on-click-backward": "tz_down",
            "on-scroll-up": "shift_up",
            "on-scroll-down": "shift_down"
        }
    },
```
it still doesnt refresh the second hand its frustrating. i wanted it to be live like a real clock. pls tell me if its possible or not

**Comment by its-19818942118** [comment]
? only ```%T```? does that come in 24h format?

**Comment by its-19818942118** [comment]
oh no wait it is updating now idk what went wrong but it just works. thanks for dealing with me

**Comment by arkmalcom** [comment]
This is the top Google result for this issue, so if anyone ends up here, make sure you've checked this:

https://github.com/Alexays/Waybar/wiki/Module:-Clock#troubleshooting

There is an "interval" option that you should configure to 1, since the default is 60. If you don't do this, then no matter which format you use, you'll never see seconds updated in real time.
