### ISSUE TITLE
"focused"-icon is only used when the workspace is empty

### ISSUE THREAD

**Issue by maikrhg** [Alexays/Waybar#3095]
Hello, I use Arch Linux with Sway and the current Waybar version. When I open a new workspace, the "focused" icon specified in the config is displayed. However, when I open a window, the icon is replaced by the default icon. What am I doing wrong? Here is my config:

```
    "sway/workspaces": {
        "all-outputs": false,
        "disable-scroll": true,
        "format": "{icon} {name}",
        "format-icons": {
            "urgent": "",
            "focused": "",
            "default": ""
        }
    },
```

**Comment by eerii** [comment]
I just came across this same problem, also running arch.

**Comment by ordy** [comment]
It looks like the icon priority has been messed up on focused defaults. Because it used to work just fine on 0.9.24.
Workspace icons need to indeed change icon when focused.

https://github.com/Alexays/Waybar/blob/ddc767cd815a7c429bc4dd7f185fad93e485271d/src/modules/sway/workspaces.cpp#L391

On an expected behavior should indeed have the focused icon replace the default, regardless of a clean or dirty workspace (unless of course the workspace is on the high-priority-named array).

**Comment by rplanchuelo** [comment]
Same problem, also running arch and Sway

**Comment by ProbablyRohan** [comment]
I had this issue using SwayFX and NixOS on latest release of waybar, changed to using the flake and it works perfectly now

**Comment by t0fik** [comment]
I've just tested Waybar 0.10.2 on Fedora 40 and it seems, that this issue is fixed.
Previously I had waybar 0.10.0, where issue were occuring.
