### ISSUE TITLE
group drawers not functioning correctly.

### ISSUE THREAD

**Issue by Spelis** [Alexays/Waybar#3221]
best way i can show this is through a video.

https://github.com/Alexays/Waybar/assets/152774420/7552a26b-fca2-4a7b-bd99-dc7b942fe091

so it doesn't let me extend it fully while also hovering an element.
(also i dont know if this already exists already or if its even possible but would be nice if there was a `overflow`-like style property like in css)

**Comment by haug1** [comment]
Are you using 0.10.3? The approach for hover on groups just changed slightly in this release. Would be helpful to know for sure that you are on the latest version and whether it's still problematic for you compared to earlier version.

**Comment by Spelis** [comment]
Well that was yesterday on git version and I have no idea what version number that was. I'll check if it works today

**Comment by Spelis** [comment]
currently installing waybar-git-r2429.09142fa3-1....
nope, waybar-git-r2429.09142fa3-1 still has that issue (arch linux user repo)
waybar-git does build from this github repo right?

**Comment by Spelis** [comment]
also, AUR is on waybar-0.10.2-2 for normal version.
0.10.2-2 version works fine but does not have the tooltips functioning properly
and git version the drawers dont work.

**Comment by haug1** [comment]
Then you can build 0.10.3 from source by checking out master or wait for it to become available in your repository. It may fix your issues. Feel free to update or closing this issue depending on whether it persists after 0.10.3. :)

**Comment by haug1** [comment]
Would you mind sharing your CSS and group config. I may have a closer look at this in the evening.

**Comment by Spelis** [comment]
`
	"group/group-info": {
		"orientation": "inherit",
		"drawer": {
			"transition-duration": 500,
			"children-class": "not-info",
			"transition-left-to-right": true
		},
		"modules": [
			"custom/infolabel",
			"pulseaudio",
			"cpu",
			"battery",
			"memory",
			"custom/kb",
			"backlight",
			"custom/pacman",
			"disk"
		]
	},
`

`#group-info {
	background: @color1;
	margin: 2px 2px 2px 5px;
	padding: 0 5px;
	padding-right: 0;
	border-radius: 16px 100px 100px 16px;
}
`

**Comment by haug1** [comment]
It seems that adding padding or margin to the group itself causes the issue. It may not be ideal, but as a workaround you can add it on your "infolabel" component inside the group instead.

**Comment by haug1** [comment]
I've attempted the following fixes, but none of them are good:

- put "box" inside another Gtk::Box 
this simply seems to change nothing, maybe it introduced some new issues I wasn't able to test.

- put styling target attributes(gtk name and gtk styling context class) on the event_box wrapper instead
this just seems to ignore padding and margin attributes. again maybe it introduced some other issues I didn't test.

- put styling target attributes on the revealer box and first widget instead
this works, but not good enough, because i.e border radius will be around the first widget and the revealer box individually. again, probably other possible side-effects as well. 

So my conclusion is that I don't know how to elegantly solve this without moving back to [this issue](https://github.com/Alexays/Waybar/issues/3029#issuecomment-2007042802) where the group drawer reveal effect would get stuck open. Of course, the current situation is not great also because it's probably fairly common for users of the group drawer to try to put margin or padding on there. So it's bound to be at least a source of confusion for a lot of users, I think.

**Comment by Spelis** [comment]
ah ok ill close this one :)
