### ISSUE TITLE
Text of sway/window is not aligned like other modules

### ISSUE THREAD

**Issue by nicball** [Alexays/Waybar#3316]
Here is a picture of my bar with a huge font for sway/window and explicit borders for the sake of debugging.

![image](https://github.com/Alexays/Waybar/assets/6604584/aabb3cc9-9928-477f-817c-82a6b6a88091)

The text seems to lay at bottom, not centered vertically.

Here is the other way around, making everything else big.

![image](https://github.com/Alexays/Waybar/assets/6604584/628477d8-1ed8-427e-9909-001521613263)

The other modules doesn't touch the bottom.

I don't know anyways to align the text with CSS. Should it be "corrected" in the GTK code of sway/window?

**Comment by RobertMueller2** [comment]
sway/window itself doesn't really do anything magic regarding the GUI elements. The main difference of the window modules (hyprland and dwl as well) to most of the other modules is that the window modules use AAppIconLabel (extending AIconLabel) as base class, which has an encapsulating box element.

I don't want to say there isn't an issue, but the encapsulating box means that you have two levels of padding/margin/border rather than one.

**Comment by nicball** [comment]
I've checked` GTK_DEBUG=interactive`, those surrounding elements has 0 padding/margin. Also the workspace module on the left also has surrounding boxes and they looks fine. Maybe this is an `AAppIconLabel` specific issue?

**Comment by RobertMueller2** [comment]
Ok, I think now I begin to understand the comparison of the different font sizes. Honestly, I'm finding it very difficult to see. 

What I did notice is that y and p in waybar-unwrapped have a descender, while none of the letters/numbers in the right modules do. So I'm wondering, what happens if any of the other modules did have anything with a descender in them? Does the middle then still reach deeper than the right ones?

I'm using sway/window next to mpris. (I don't like how it looks, but couldn't come up with anything better. :P) Now I don't know if they're correct, but at least I don't see a difference between them. Mpris is just using a normal ALabel.

![satty-20240604-21:07:50](https://github.com/Alexays/Waybar/assets/29629287/a3fc4c47-b59c-431c-825e-ea9071c2e169)

**Comment by nicball** [comment]
I think you're right. There's nothing specific with sway/window.

A better way to put it is that by default the center of 'x' is not at the center of height of waybar, which is more obvious when font is big with no padding. Normally when there's padding, the offset is much less noticeable.

But I guess that's just how font rendering works?
