### ISSUE TITLE
Use Format replacements in action

### ISSUE THREAD

**Issue by zooeywm** [Alexays/Waybar#3374]
Hello maintainers, first of all, thanks for your excellent work on this project. It has been incredibly useful for me.

I am currently experiencing an issue with: When I'm trying to write a minimizer for Hyprland with `wlr/taskbar`'s `on-click-right`.

The ideal action for me looks like this:

```
"on-click-right": "bash -c '[ '$(hyprctl clients -j | jq -r '.[] | select(.title == {title})' | jq -r '.workspace.name')' == 'special:minimized' ] && hyprctl dispatch movetoworkspace +0,title:{title} || hyprctl dispatch movetoworkspacesilent special:minimized',title:{title}",
```

The only thing miss for me is using the `title` in action

Or is there any other methods to achieve this?

**Comment by RobertMueller2** [comment]
I might be wrong, but right now I don't really see a way to do this from within wlr/taskbar.

Here's an alternative workflow suggestion:
- add a shortcut to your hyprland config that sends the active window to special:minimized workspace
- add a shortcut to your hyprland config that starts a script which
  -  pulls a list of windows on special:minimized workspace
  - opens dmenu/rofi/... to display them
  - runs hyprctl dispatch to get the selected window back

It might not be as pretty, but it has the advantage that it should be available right now. ;)

Regarding your feature request, I think it's a nice idea for user scripts called from wlr/taskbar to have access to certain window information, but:
- wlr/taskbar wasn't really supposed to call user scripts, the on-clicks are really meant for module internal wayland actions as documented in the manpage
  - see https://github.com/Alexays/Waybar/blob/ca3877d0b8e8e6cb484c6a9c6d5dcaff5fab0b74/src/modules/wlr/taskbar.cpp#L535
  - that it partially does that now is because it is not fully integrated with the current version of AModule, which from my point of view is a bug. The scripts are called from the whole module widget, not from individual window button widgets, which makes it impossible to have any window specific information that way
  - a bigger rework based on the given shortcoming could address this in the future, maybe
- I would be concerned about replacements in commands, because the input is quite arbitrary. E.g. if it's a shell terminal, the title can be set via a prompt command within the shell and could contain a lot of things. A better approach would be to make the information available via environment variables

**Comment by RobertMueller2** [comment]
BTW, title or app_id aren't necessarily unique, which limits the usefulness of setting them for use in scripts.

**Comment by zooeywm** [comment]
Sorry for the late reply, I've made some confusions on taskbar's feature. I turns to use rofi, it works great for me, thanks :100:
