### ISSUE TITLE
Network module does not updating

### ISSUE THREAD

**Issue by niktob560** [Alexays/Waybar#354]
Waybar v0.6.6  
After restarting netctl-auto network module shows disconnected status until restart waybar  
No info about that with --log-lеvel trace  
ArchLinux with linux 5.1.0

**Comment by niktob560** [comment]
Restarting of iface or reconnecting to wifi will cause too

**Comment by Alexays** [comment]
Does it also do that on master?

**Comment by ReekyMarko** [comment]
I'm also experiencing this on Arch Linux using Sway. I tried the `waybar-git` package from the AUR and the issue is still there. For me it has gotten to the point where it shows disconnected most of the time. When I restart waybar it show connected for about 20 seconds and then it goes back to disconnected

**Comment by Alexays** [comment]
c06725aa69b46e7eee605e86642679067744c553 5ae5821929ee09726bc9908c09c20424bd3b0793 Should fix that or improve it :)

**Comment by ReekyMarko** [comment]
Yeah, much better now! Haven't had a false disconnect in a while

**Comment by niktob560** [comment]
nice fix :)
