### ISSUE TITLE
glitch / lag once a while with hyprland

### ISSUE THREAD

**Issue by littleblack111** [Alexays/Waybar#3574]
this is the original issue on hyprland: https://github.com/hyprwm/Hyprland/issues/7624 i originally thought it was a compositor/wm issue for obv reasons. but after having enough of this shit. I disabled stuff line by line and restarted the compositor. and it stopped doing that until i commented waybar... so i guess i have to put this into a waybar issue... and its prob not a env issue since i initialy tried once without any env= set. and yes after waybar launching. killall waybar solves it as well... I really want to use waybar. but more significantly, dont wanna lag everything as a whole.... please fix asap. idk why no one had this issue b4...

**Comment by littleblack111** [comment]
@Alexays pls fix. also these are some logs that will happen exactly at the stun:
```
[2024-09-22 15:15:26.336] [debug] Received SIGCHLD in signalThread
[2024-09-22 15:15:26.336] [debug] Cmd exited with code 0
[2024-09-22 15:15:26.372] [debug] Cmd exited with code 0
[2024-09-22 15:15:26.372] [debug] Received SIGCHLD in signalThread
```
my guess is that theres smth during the update that will stun the screen

**Comment by YendisFish** [comment]
I'm having this issue as well! It's my first day using waybar (and hyprland for that matter) and unfortunately I'm already starting to look for an alternative bar... but waybar really seemed like the obvious choice. Unfortunate...

I theorize it has something to do with one of the modules that the bar uses... something that updates on the bar and changes its state. I just don't know which one it might be...

**Comment by littleblack111** [comment]
lol ive been surffering from this since day 1

**Comment by YendisFish** [comment]
I mean... I'm thinking about forking this, finding the issue, and attempting to resolve it myself... just don't have the time recently. I'll come back to this issue thread if I do. I sincerely doubt enough people are getting this issue for the creator to even care.

**Comment by kiecla** [comment]
If you use Sway with Waybar do you see the same lag? That way you can isolate the issue to an interaction between Waybar and Hyprland.
Does the issue persist with a fresh install of Hyprland with only Waybar and the minimum required configuration to get your system going? That way you can rule out any other interactions beyond Waybar, Hyprland, and your configuration/machine.
I also have Hyprland and Waybar on NVIDIA and I'm not having the same issue as you, and I don't think many are, because Waybar is quite a common choice on Hyprland so we would have heard more about it by now.
It'll be easier for the devs to do something if they have a more concrete problem to deal with.

**Comment by littleblack111** [comment]
what modules do you have?

**Comment by littleblack111** [comment]
seemed fixed after some updates
