### ISSUE TITLE
nm-applet in tray shows menu on right click only

### ISSUE THREAD

**Issue by pedrocr** [Alexays/Waybar#360]
I've been trying out Waybar and used nm-applet in the tray. It seems to work but the menu that should show up as a dropdown with a left-click only shows up centered in the screen with a right click. Is that what's supposed to happen? 

If this is correct the usability is a bit off. The usual way of using the applet is to click it and drop down into whatever option you want. Instead I have to right click and then navigate to the center of the screen to change stuff.

**Comment by pedrocr** [comment]
If it helps, I get this error every time the popup is opened:

```
(waybar:22058): Gdk-WARNING **: 19:41:10.606: Couldn't map as window 0x560f40446c90 as popup because it doesn't have a parent
```

**Comment by pedrocr** [comment]
This is probably the same as #63 although that doesn't include the issue of the menu showing up with right click instead of left-click.

**Comment by Alexays** [comment]
Dropdown is centerd in the screen cause of gtk removed some code, and now we'll need to implement xdg-popup, otherwise i'll try to look for the click behaviour :)

**Comment by Alexays** [comment]
Fixed with ec75be0bc33f66c10aa43a1ee81de624d84c704f

**Comment by pedrocr** [comment]
Thanks, tested it and left click now works but right click still does as well. The code seems to be written that way but don't know if that's the common behavior of these applets.

**Comment by alebastr** [comment]
@Alexays, https://github.com/Alexays/Waybar/commit/ec75be0bc33f66c10aa43a1ee81de624d84c704f breaks default left click action of tray items (i.e. open application window). Now they are only able to show menu with both mouse buttons.
`nm-applet --indicator` is actually not supposed to show menu on left click as it does not set ItemIsMenu flag.

**Comment by Alexays** [comment]
@alebastr Yeah i had seen that too but since on a xembed tray it worked like that...

**Comment by alebastr** [comment]
@Alexays, so apparently libappindicator uses their own version of dbus protocol: https://bazaar.launchpad.net/~indicator-applet-developers/libappindicator/trunk.16.10/view/head:/src/notification-item.xml.
Since it has neither 'Activate' method nor 'ItemIsMenu' property, we could set item_is_menu for all libappindicator applets. Now, the only problem is how to distinguish them.

If we assume that whoever implements the full spec and cares about left clicks will always set ItemIsMenu, it would be sufficient to revert https://github.com/Alexays/Waybar/commit/ec75be0bc33f66c10aa43a1ee81de624d84c704f and initialize Item::item_is_menu to true. That works for Qt apps and I haven't found any more implementations of SNI.
