### ISSUE TITLE
Putting " \ " in the config.jsonc will crash waybar in any module or module name or format types etc.

### ISSUE THREAD

**Issue by Set2Minecraft** [Alexays/Waybar#3675]
Waybar v0.11.0

To reproduce, add a \ into any part of the config that is uncommented, does not matter if module with \ is called or not, if its just a name or part of the formatting output

**Comment by RobertMueller2** [comment]
I wouldn't call that a crash. Waybar doesn't start because the config file is invalid that way. Not starting when the config is not valid is entirely sensible to me.

Outside of strings, `\` is not a valid character in json, and inside of strings, `\` starts an escape sequence in json. If you want to use `\` in a string in json, you have to escape it like `\\`.

See 
https://datatracker.ietf.org/doc/html/rfc8259
https://ecma-international.org/publications-and-standards/standards/ecma-404/
for details. Jsonc is a superset of json, so the same considerations apply to it.

I don't think there's a bug here.

**Comment by Set2Minecraft** [comment]
Oh, yea I would agree. I have only used jsonc for waybar so I had no idea, thanks for the help!
