### ISSUE TITLE
libspdlog.so.1.13 needed installed version of waybar = 0.11.0-4

### ISSUE THREAD

**Issue by KipKat13** [Alexays/Waybar#3792]
Hi there!

Every time I try to run Waybar I get the error that I need spdlog 1.13, whilst I have 1.15 installed and Waybar wouldn't need 1.13

So why doesn't it want to run?
I tried to uninstall Waybar and do yay -S spdlog-1.13.0-1-x86_64.pkg.tar.zst but I get an error that:

warning: downgrading package spdlog (1.15.0-1 => 1.13.0-1)
resolving dependencies...
looking for conflicting packages...
error: failed to prepare transaction (could not satisfy dependencies)
:: installing spdlog (1.13.0-1) breaks dependency 'libspdlog.so=1.15-64' required by waybar

I dont know what to do anymore, installed waybar and removed it a couple of times to, or tried to download the waybar-git. But they all give the same message.
![2024-11-25-184438_hyprshot](https://github.com/user-attachments/assets/18922549-294a-47ee-9c99-ecd5410be7d2)

**Comment by TripleTrable** [comment]
the reason is, that during the PGKBUILD of waybar it pins the current version of libspdlog.so.

My solution was to download the package (PKGBUILD) and change the dependency from "libspdlog.so to" spdlog and then building and installing it (see my pkgbuild testing mirror [here](https://github.com/TripleTrable/aur-overlay/commit/cef2fca46c4024858cbaf5be5e0d92e581ebbcef#diff-71b7f8ca63dc0555c9b7f349d9e9a71e71500d2569b7d48e7431427e29baf34bR21) line 21). This change causes the package to depend on any version of spdlog (at least on my machine :smile:). 

Another solution in the AUR is (it is waybar-git but the same error):
https://aur.archlinux.org/packages/waybar-git#comment-998777

**Comment by TripleTrable** [comment]
what is your waybar version?

**Comment by KipKat13** [comment]
your previous comment worked too! thanks for the help @TripleTrable ! I changed the line in PKGBUILD

**Comment by KipKat13** [comment]
got it, thank you for your help and explanation! works good now
