### ISSUE TITLE
Empty format string does not hide a module

### ISSUE THREAD

**Issue by JadElClemens** [Alexays/Waybar#533]
In the default configuration, it is implied that an empty format string for a module will hide it - see `format-good` under `battery`.

This is not working for me - I have set `"format-disconnected": ""` under `network` to hide the module when no interface is connected, but when disconnected, I simply get an empty network module with only padding. I'm sure that the module is in the disconnected state as the relevant CSS rules are still taking effect.

**Comment by Alexays** [comment]
We may need to abstract it like in my WIP PR.
https://github.com/Alexays/Waybar/pull/404/files#diff-72e7598d88853f826bdaced2914e6337R48
In the meantime, it's done with c885be369e4f2a822b1e3635b8cdca098c50f113

**Comment by jvanbruegge** [comment]
I am not sure why, but this does not work for me (when compiling master myself). 
![grafik](https://user-images.githubusercontent.com/1529052/72445673-5ea80f00-37b2-11ea-8146-ca7a596b2585.png)
As seen in this image, both red network modules should not be there because they are disconnected and thus have an empty format string.
