### ISSUE TITLE
pulseaudio module disabling itself if no app using pulseaudio already started

### ISSUE THREAD

**Issue by v0idifier** [Alexays/Waybar#632]
`[warning] module pulseaudio: Disabling module "pulseaudio", pa_context_connect() failed: Connection refused`

starting an app that uses pulseaudio, then restarting waybar, fixed it.

**Comment by JohnHolmesII** [comment]
I have had this exact issue as well.

**Comment by leonm1** [comment]
I have experienced this error, and it is likely that pulseaudio is [loaded via a socket](https://wiki.archlinux.org/index.php/PulseAudio#Running) on your machine, so it is not actually started until an application using it is started.

For me, running `systemctl --user enable pulseaudio` (no sudo) fixes the behavior and coexists peacefully with other DEs running on my system that auto-start pulseaudio themselves.

**Comment by JohnHolmesII** [comment]
I don't even use sytemd.

The "issue" is [here](https://github.com/Alexays/Waybar/blob/master/src/modules/pulseaudio.cpp#L24), where it seems quite intentional to not spawn a pulse server if it doesn't exist. I think I can understand why this was done, I don't think passing that flag makes sense for something like a statusbar. When I load my machine, sway is the first thing I start. Of course there's no audio server running. By using the module from waybar, I am choosing to have one started. I don't want to have to open a youtube video and then reload sway just to have the pulse module show up lol. I think it is OK for waybar to start it; that is the way pulseaudio was designed.

I recommend removing that flag from the connect request. I'm not interested in adding a hook to runit.

**Comment by Alexays** [comment]
@JohnHolmesII we can change the flag to `PA_CONTEXT_NOFAIL` instead.
I'm ok to change that, you can make a PR 😃

**Comment by JohnHolmesII** [comment]
Fixed by #651
