### ISSUE TITLE
Cannot Build Due to Linking Error with `libfmt`

### ISSUE THREAD

**Issue by nhubbard** [Alexays/Waybar#73]
Hi there. Just built Waybar for the first time. After the build is finished and installed, `waybar` refuses to start with this very specific and therefore un-Googleable error:
```
waybar: symbol lookup error: waybar: undefined symbol: _ZN3fmt2v58internal10basic_dataIvE23ZERO_OR_POWERS_OF_10_32E
```
I presume that this is because of a linking issue with libfmt; any idea as to what is wrong here?

**Comment by nhubbard** [comment]
I will close my own issue - Meson was attempting to link with version 3.2.0 on my system.

**Comment by jeefberkey** [comment]
@nhubbard can you share how you fixed this? I've been seeing this issue as well.

**Comment by nhubbard** [comment]
I had to clone the latest version of `libfmt` from GitHub, install it on my system, and then rebuild using Meson. I ran into an issue after this, mainly that my configuration does not work when running - it "starts", but does not "run".

**Comment by jeefberkey** [comment]
Hm, isn't that kinda what meson does during build? I'm not very familiar with compiled languages, but from poking around I learned that:

* fmt is wrapped using meson build tools because the system fmt is likely too old
* the wrapfile is in subprojects, and there is a compile fmt in the build dir after running the build
* running the waybar executable from the build directory works, and ldd says it's linked to the fmt in the build dir
* running the very same(?) waybar binary from /usr/local/bin/waybar fails with the fmt error, and it shows it linking to a different fmt

**Comment by Alexays** [comment]
@jeefberkey By the 1.1.3 tag you mean the 0.1.3 waybar tag?

**Comment by jeefberkey** [comment]
@Alexays yeah, that's what I meant to type.
