### ISSUE TITLE
[feature request] ability to display the values in the network module in bytes/megabytes per second

### ISSUE THREAD

**Issue by jdbm8992** [Alexays/Waybar#804]

**Comment by excellentname** [comment]
If you mean using bytes as an alternative to using octets as the unit/symbol e.g. 25MB/s instead of 25Mo/s, then I would be interested in adding it.

**Comment by jdbm8992** [comment]
@excellentname waybar currently displays it in Mbit/s by default, but I would like it to display it in MB/s instead of Mbit/s.

Example: instead of displaying 100Mbit/s...in MB/s it should be 12,5 MB/s.

**Comment by excellentname** [comment]
@jdbm8992 I assume you're talking about the {bandwidthDownBits}/{bandwidthUpBits} format replacements?

**Comment by jdbm8992** [comment]
@excellentname yeah exaclty

**Comment by excellentname** [comment]
@jdbm8992 so you can use {bandwidthDownOctets}/{bandwidthUpOctets} which is the same thing as bytes per second but the symbol will be 'o/s' not 'B/s'. So to use your example, {bandwidthDownBits} would give 100Mb/s and {bandwidthDownOctets} would give 12.5Mo/s.
Currently there is no way to use 'B/s', but I would like to add an option or something to be able to use 'B/s' instead of 'o/s'. I hope that made sense.

**Comment by jdbm8992** [comment]
@excellentname I've changed it now and now it's showing in octets. Should I close the issue?
