### ISSUE TITLE
Some modules crash, when i click on it

### ISSUE THREAD

**Issue by DjinNO** [Alexays/Waybar#859]
Upper right corner
![image](https://user-images.githubusercontent.com/15555838/93665505-9cff7780-fa7f-11ea-846a-048ffb376cc8.png)
Click on network module => and now:
![image](https://user-images.githubusercontent.com/15555838/93752760-c77c3c80-fc07-11ea-8169-a7abc47b31a4.png)

Arch Linux
Waybar v0.9.3

**Comment by Alexays** [comment]
Seems to be the same screenshot, no?

**Comment by DjinNO** [comment]
Sorry. Fixed.
network and two my custom modules (vpn, bluetooth) crashed, after i tried to click on volume module
I tried to run waybar with debug mod, but debug show nothing

**Comment by Java-boi** [comment]
> I tried to run waybar with debug mod, but debug show nothing

I got some warnings which may help...

[2020-09-21 12:31:46.665] [info] Resources files: /home/will/.config/waybar/config, /home/will/.config/waybar/style.css
[2020-09-21 12:31:46.678] [warning] For a functional tray you must have libappindicator-* installed and export XDG_CURRENT_DESKTOP=Unity

** (waybar:22892): WARNING **: 12:31:46.710: gtk-layer-shell was not compiled with support for GTK v3.24.23, program may crash

** (waybar:22892): WARNING **: 12:31:46.712: gtk-layer-shell was not compiled with support for GTK v3.24.23, program may crash

(waybar:22892): Gdk-WARNING **: 12:31:50.110: Couldn't map window 0x5610edd18b70 as subsurface because its parent is not mapped.

** (waybar:22892): WARNING **: 12:31:50.110: gtk-layer-shell was not compiled with support for GTK v3.24.23, program may crash

**Comment by wmww** [comment]
I doubt this is GTK Layer Shell related. `gtk-layer-shell was not compiled with support for GTK v3.24.23, program may crash` looks scary, but I tested and there doesn't seem to be any relevant GTK changes recently so I doubt that's the cause. Regardless I just updated master so if you pull the latest GTK Layer Shell you shouldn't get that. The `Couldn't map window 0x5610edd18b70 as subsurface because its parent is not mapped.` warning is harmless but I haven't figured out how to suppress it yet.

**Comment by wmww** [comment]
Just to be sure, someone who experiences the Waybar crash can try running gtk-layer-demo (You'll probably need build GTK Layer Shell yourself so you can configure it with the `-Dexamples=true` option). If clicking the popup menu works there then it's not a GTK Layer Shell issue.

**Comment by 0xC0ncord** [comment]
I'm having a similar issue. In my case I am using the `custom/mpd` example module as seen [here](https://github.com/Alexays/Waybar/wiki/Module:-Custom#mpd). This is my exact configuration:

When I click on the module, it performs the command in `on-click`, in this case, `mpc toggle` which succeeds. At the same time, the module disappears from waybar and I have to restart it in order for the module to reappear. Clicking on it again has the same effect, toggling the state of mpd and then causing the module to disappear again.

**Comment by 0xC0ncord** [comment]
I just also noticed that of the modules that die when this happens, if there are multiple present at the same time and any one of them dies in this way, all other custom modules die as well.

**Comment by 0xC0ncord** [comment]
Here is a quick video demonstrating the problem: https://imgur.com/a/J3cuMyp

I show three custom modules that are affected by this: the `custom/mpd` module on the left, `custom/notifications` (the bell), and `custom/screenrecord` (video camera). As soon as I click the `custom/notifications` module, all three of these modules die.

**Comment by DjinNO** [comment]
@0xC0ncord  Which tool you used to record this gif?

**Comment by 0xC0ncord** [comment]
> @0xC0ncord Which tool you used to record this gif?

[wf-recorder](https://github.com/ammen99/wf-recorder), but Imgur converted the original mp4 to gif.

**Comment by DjinNO** [comment]
After last pacman -Syu on my Arch Linux problem was fixed
